### ISSUE TITLE
Invalid format importing .mqo files

### ISSUE THREAD

**Issue by IndolentKheper** [nutti/blender-mqo#14] opened 2022-03-15 02:20 UTC
**System Information**
  
* OS: Windows 10
* Blender version: 2.92, 2.83
* Add-on version: 1.0, 1.2, newest
* Metasequoia version: [e.g. 4.6.1]

**Expected behavior**  
Can't import any .mqo created from FFXI models. I don't have Metasequoia right now but I know they were all valid .mqo that worked in Metasequoia.

**Description about the bug** 
Tried multiple files, all result in errors like this:

Python: Traceback (most recent call last):
  File "C:\Users\kheper\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender_mqo\ops.py", line 690, in execute
    self.import_prefix if self.add_import_prefix else "")
  File "C:\Users\kheper\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender_mqo\ops.py", line 330, in import_mqo_file
    mqo_file.load(filepath)
  File "C:\Users\kheper\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender_mqo\utils\mqo_file.py", line 1833, in load
    self._objects.append(self._parse_object(line))
  File "C:\Users\kheper\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender_mqo\utils\mqo_file.py", line 1736, in _parse_object
    obj.add_faces(self._parse_face(line))
  File "C:\Users\kheper\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender_mqo\utils\mqo_file.py", line 1566, in _parse_face
    raise RuntimeError("Invalid format. (line:{})".format(first_line))
RuntimeError: Invalid format. (line:b'face -1 {')

location: <unknown location>:-1

**Screenshots/Files** [Optional]  
Want to attach an affected .mqo but the file type isn't supported here.

**Additional comments** [Optional]
Tried in 1.0 and 1.2, same problem.

Thank you very much for your work on this add-on.

**Comment by IndolentKheper** [comment] 2022-03-15 02:27
Just tried an old version of Metasequoia 3, the files load in there, and if saved in Metasequoia 3 can then be imported into Blender. However, the files are invalid if not processed by Metasequoia prior to importing into Blender. If created by another program the .mqos are seen as invalid until saved in Metasequoia.

**Comment by nutti** [comment] 2022-03-15 03:43
@IndolentKheper 

Is it possible to upload .mqo file anywhere (Google Drive, or other storage service)?
It is difficult for me to tackle this issue without .mqo file.

**Comment by Arenovas** [comment] 2022-03-24 03:22
Pretty sure I'm having the exact same issue as the bug reporter, exported an MQO file with a program and the addon refuses to import it due to an invalid format. I don't have Metasequoia to try it out myself but I can supply the file I'm trying to import in the hopes of helping fix this issue. [RoomsAndFloor.zip](https://github.com/nutti/blender-mqo/files/8338151/RoomsAndFloor.zip)

**Comment by nutti** [comment] 2022-03-24 07:56
@Arenovas 

I can reproduce your error. Thanks for sharing!
I think this issue is different from @IndolentKheper .
But I can fix your issue :)

Also I notice you that your MQO file has lots of object, so it will take lots of time to import.

**Comment by nutti** [comment] 2022-03-24 09:23
@Arenovas 

Fixed the issue against your uploaded MQO file.

@IndolentKheper 

Is it possible to upload your file which raises your issue?
I think uploading MQO file is best way to solve the issue quickly.

**Comment by Arenovas** [comment] 2022-03-24 21:23
Thanks! Hopefully I'll have no problems with the other MQO files I got from that export with that fix as well. And to note for the other user, compress the file into a ZIP file and then you can upload it to Github.

**Comment by nutti** [comment] 2022-03-31 06:36
Close this issue for now because original reporter does not reply this issue.

@Arenovas 

Thanks for your information.

@IndolentKheper 

If you see this issue and try to upload your MQO file, please ping me again.

**Closed by nutti** 2022-03-31 06:36 UTC
Labels: bug
